#!/bin/bash

curl -s http://thesaurus.com/browse/"$1" | grep 'Antonyms\|<span class="text">' | sed -e 's/\s\s\s*\|<[^>]*>//g' -e 's/<div\sclass="synonym-description">.*//g' -e 's/\(.*\)/    \1/g' -e 's/\s\s\s\s\(Antonyms\sfor\s.*\)/\n\1/g' -e '1 s/\s\s\s\s\(.*\)/\1/'
